apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: sebastiaomarcos/gitops
  newTag: c58c801b289f278fd588776fc29adf8f1af4b7e9
